all:
  hosts:
    brutal_grounds_distributed_server:
      ansible_connection: ssh
      ansible_host: "{{ server_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ private_key }}"